AnswerPoortal/Models/Question.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnswerPoortal.Models

    
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new List<Answer>();
            this.QuestionCopies = new List<QuestionCopy>();
        }

        public int id { get; set; }
        [Display(Name = "Title")]
        public string title { get; set; }
        [Display(Name = "Text")]
        public string text { get; set; }
        [Display(Name = "Picture")]
        public byte[] pic_path { get; set; }
        [Display(Name = "Locked")]
        public bool status { get; set; }
        [Display(Name = "Date Created")]
        public System.DateTime creationDate { get; set; }
        [Display(Name = "Date Locked")]
        public Nullable<System.DateTime> lockDate { get; set; }
        public int idAccount { get; set; }

        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Answer> Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<QuestionCopy> QuestionCopies { get; set; }
    }
}

AnswerPoortal/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AnswerPoortal.Models;

namespace AnswerPoortal.Controllers
{
    public class QuestionsController : Controller
    {
        private AnswerPortalEntities db = new AnswerPortalEntities();

        // GET: Questions
        public ActionResult Index()
        {

            var query =
                      from o in db.Questions
                      join a in db.Accounts on o.idAccount equals a.id
                      where a.email == User.Identity.Name
                      select new { o.Account, o.Answers, o.creationDate, o.id, o.idAccount, o.lockDate, o.pic_path, o.QuestionCopies, o.status, o.text, o.title};
            var questions = query.ToList();
            List<Question> li = new List<Question>();
            foreach (var q in questions) {
                Question qu = new Question();
                qu.Account = q.Account;
                qu.Answers = q.Answers;
                qu.creationDate = q.creationDate;
                qu.id = q.id;
                qu.idAccount = q.idAccount;
                qu.lockDate = q.lockDate;
                qu.pic_path = q.pic_path;
                qu.QuestionCopies = q.QuestionCopies;
                qu.status = q.status;
                qu.text = q.text;
                qu.title = q.title;
                li.Add(qu);
            }
            //var questions = db.Questions.Include(q => q.Account);
            return View(li);
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            AnswerPortalEntities db = new AnswerPortalEntities();
            var cong = db.Configs.First();
            ViewBag.NumberOfAnswers = cong.answerPriceK;
            //ViewBag.idAccount = new SelectList(db.Accounts, "id", "name");

            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "title,text,ImageToUpload,status, Answers")] Question question)
        {
            question.pic_path = new byte[question.ImageToUpload.ContentLength];
            question.ImageToUpload.InputStream.Read(question.pic_path, 0, question.pic_path.Length);
            if (ModelState.IsValid)
            {
                for(int i = 0; i<question.Answers.Count; i++) {
                    if (i == 0) question.Answers[i].isCorrect = true;
                    else question.Answers[i].isCorrect = false;
                    }

               
                DateTime dt = System.DateTime.Now;
                var query = db.Accounts.Where(s => s.email == User.Identity.Name);
                Account acc = query.FirstOrDefault();
                question.idAccount = acc.id;
                question.creationDate = dt;
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var cong = db.Configs.First();
            ViewBag.NumberOfAnswers = cong.answerPriceK;
            ViewBag.idAccount = new SelectList(db.Accounts, "id", "name", question.idAccount);
            return View();
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.idAccount = new SelectList(db.Accounts, "id", "name", question.idAccount);
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,text,ImageToUpload,status,idAccount,creationDate, lockDate, Answers")] Question question)
        {
            var query = db.Accounts.Where(s => s.email == User.Identity.Name);
            
            //Account acc = query.FirstOrDefault();
            //question.idAccount = acc.id;
            var config = db.Configs.Find(1);
           // Question questionorig = db.Questions.Find(question.id);
           if (question.ImageToUpload != null) { 
            question.pic_path = new byte[question.ImageToUpload.ContentLength];
            question.ImageToUpload.InputStream.Read(question.pic_path, 0, question.pic_path.Length);
            
            }
            if (ModelState.IsValid)
            {

                //if (questionorig.status == true && question.status == false && (acc.tokenNum < config.unlockPriceM)) return View("UnlockFailed");
                //else if (questionorig.status == true && question.status == false && (acc.tokenNum >= config.unlockPriceM)) {

                //  acc.tokenNum = acc.tokenNum - config.unlockPriceM;
                //}

                // if (questionorig.status == false && question.status == true) { question.lockDate = DateTime.Now; }
                //db.Entry(acc).State = EntityState.Modified;
                
                db.Entry(question).State = EntityState.Modified;
                if (question.ImageToUpload == null) db.Entry(question).Property(x => x.pic_path).IsModified = false;
                foreach (var answ in question.Answers) {
                    db.Entry(answ).State = EntityState.Modified;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idAccount = new SelectList(db.Accounts, "id", "name", question.idAccount);
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            question.Account = null;
            db.Questions.Remove(question);
          
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET: Questions/Delete/5
        public ActionResult Lock(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Lock")]
        [ValidateAntiForgeryToken]
        public ActionResult LockConfirmed(int id)
        {

            Question question = db.Questions.Find(id);
            question.lockDate = System.DateTime.Now;
            question.status = true;
            db.Entry(question).Property(x => x.status).IsModified = true;
            db.Entry(question).Property(x => x.lockDate).IsModified = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Questions/Delete/5
        public ActionResult Unlock(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Unlock")]
        [ValidateAntiForgeryToken]
        public ActionResult UnlockConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            Account acc = question.Account;
            Config conf = db.Configs.Find(1);
            if (acc.tokenNum >= conf.unlockPriceM)
            {
                acc.tokenNum = acc.tokenNum - conf.unlockPriceM;
                question.status = false;
                db.Entry(question).Property(x => x.status).IsModified = true;
                db.Entry(acc).Property(x => x.tokenNum).IsModified = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else return View("UnlockFailed");

   
            
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AnswerPoortal/Views/Questions/Create.cshtml
@model AnswerPoortal.Models.Question

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Questions", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal col-md-offset-1">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-1 labell" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-1 labell", })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageToUpload, htmlAttributes: new { @class = "control-label col-md-1 labell" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImageToUpload, new { type = "file" })
                @Html.ValidationMessageFor(model => model.ImageToUpload, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-1 labell" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.status)
                    @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
      
            @for (int i = 0; i < ViewBag.NumberOfAnswers; i++)
            {
                int o = i + 1;

                if (i == 0) { }
                <div class="col-md-offset-2 form-group col-md-6">

                    <h5>@if (i == 0)
                    {
                        <b><span style="color:green">(Correct)</span></b>
                    } Answer  @o </h5>
                    <div class="form-style">

                       

                        @Html.LabelFor(model => model.Answers[i].index, htmlAttributes: new { @class = "control-label" })


                        @Html.EditorFor(model => model.Answers[i].index, new { htmlAttributes = new { @class = "form-control", style = "width:60px;" } })
                        @Html.ValidationMessageFor(model => model.Answers[i].index, "", new { @class = "text-danger" })
                        </div>
                        <div>

                            @Html.LabelFor(model => model.Answers[i].num, htmlAttributes: new { @class = "control-label" })


                            @Html.EditorFor(model => model.Answers[i].num, new { htmlAttributes = new { @class = "form-control", style = "width:60px;" } })
                            @Html.ValidationMessageFor(model => model.Answers[i].num, "", new { @class = "text-danger" })



                        </div>



                    @Html.LabelFor(model => model.Answers[i].text, htmlAttributes: new { @class = "control-label" })


                    @Html.EditorFor(model => model.Answers[i].text, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Answers[i].text, "", new { @class = "text-danger" })







                </div>

            }

        


            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
            </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AnswerPoortal/Views/Questions/Delete.cshtml
@model AnswerPoortal.Models.Question

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
        <dt>
            @Html.DisplayNameFor(model => model.pic_path)
        </dt>

        <dd>
            <div class="question-image">
                @HtmlHelpers.ShowImage(Model.pic_path)
            </div>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.creationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.creationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lockDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lockDate)
        </dd>


        @for (int i = 0; i < Model.Answers.Count; i++)
        {
            int o = i + 1;
            <dt>

                Answer @o
                @if (i == 0)
                {<b><span style="color:green">(Correct)</span></b>}

            </dt>


            <dd>
                @Html.DisplayFor(model => model.Answers[i].num)@Html.DisplayFor(model => model.Answers[i].index)
                @Html.DisplayFor(model => model.Answers[i].text)
            </dd>

        }


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color backlink col-md-offset-1">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AnswerPoortal/Views/Questions/Details.cshtml
@model AnswerPoortal.Models.Question

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pic_path)
        </dt>

        <dd>
            <div class="question-image">
            @HtmlHelpers.ShowImage(Model.pic_path)
                </div>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.creationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.creationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lockDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lockDate)
        </dd>


        @for (int i = 0; i<Model.Answers.Count; i++) {
            int o = i + 1;
    <dt>
            
                Answer @o
                @if (i == 0)
                {<b><span style="color:green">(Correct)</span></b>}
          
        </dt>


        <dd>
            @Html.DisplayFor(model => model.Answers[i].num)@Html.DisplayFor(model => model.Answers[i].index)
            @Html.DisplayFor(model => model.Answers[i].text)
        </dd>

        }


    </dl>
</div>
<p class="backlink">
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AnswerPoortal/Views/Questions/Edit.cshtml
@model AnswerPoortal.Models.Question

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Questions", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal col-md-offset-1">
        <h4>Question</h4>
        <hr />
        @Html.HiddenFor(model => model.idAccount)
        @Html.HiddenFor(model => model.creationDate)
        @Html.HiddenFor(model => model.lockDate)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-1 labell" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-1 labell", })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageToUpload, htmlAttributes: new { @class = "control-label col-md-1 labell" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImageToUpload, new { type = "file" })
                @Html.ValidationMessageFor(model => model.ImageToUpload, "", new { @class = "text-danger" })
            </div>
        </div>

  

        @for (int i = 0; i < Model.Answers.Count; i++)
        {
            int o = i + 1;

            if (i == 0) { }
            <div class="col-md-offset-2 form-group col-md-6">

                <h5>
                    @if (i == 0)
                    {
                    <b><span style="color:green">(Correct)</span></b>
                } Answer  @o
            </h5>
            <div class="form-style">

                @Html.HiddenFor(model => model.Answers[i].id)
                @Html.HiddenFor(model => model.Answers[i].idQuestion)
                @Html.HiddenFor(model => model.Answers[i].isCorrect)

                @Html.LabelFor(model => model.Answers[i].index, htmlAttributes: new { @class = "control-label" })


                @Html.EditorFor(model => model.Answers[i].index, new { htmlAttributes = new { @class = "form-control", style = "width:60px;" } })
                @Html.ValidationMessageFor(model => model.Answers[i].index, "", new { @class = "text-danger" })
            </div>
            <div>

                @Html.LabelFor(model => model.Answers[i].num, htmlAttributes: new { @class = "control-label" })


                @Html.EditorFor(model => model.Answers[i].num, new { htmlAttributes = new { @class = "form-control", style = "width:60px;" } })
                @Html.ValidationMessageFor(model => model.Answers[i].num, "", new { @class = "text-danger" })



            </div>



            @Html.LabelFor(model => model.Answers[i].text, htmlAttributes: new { @class = "control-label" })


            @Html.EditorFor(model => model.Answers[i].text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Answers[i].text, "", new { @class = "text-danger" })
 </div>

        }




        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
        
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AnswerPoortal/Views/Questions/Index.cshtml
@model IEnumerable<AnswerPoortal.Models.Question>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>

        <th>
           @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.creationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lockDate)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {

    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.creationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lockDate)
        </td>

        <td class="backlink">
            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
            @Html.ActionLink("Details", "Details", new { id = item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.id }) |
            @if (item.status == false) { @Html.ActionLink("Lock", "Lock", new { id = item.id })}


            else { @Html.ActionLink("Unlock", "Unlock", new { id = item.id })}
        </td>
    </tr>
}

</table>

AnswerPoortal/Views/Questions/Lock.cshtml
@model AnswerPoortal.Models.Question

@{
    ViewBag.Title = "Lock";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lock</h2>

<h3>Are you sure you want to lock this question?</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color backlink col-md-offset-1">
        <input type="submit" value="Lock" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

AnswerPoortal/Views/Questions/Unlock.cshtml
@model AnswerPoortal.Models.Question

@{
    ViewBag.Title = "Unlock";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Unock</h2>

<h3>Are you sure you want to unlock this question?</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color backlink col-md-offset-1">
        <input type="submit" value="Unock" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

AnswerPoortal/Views/Questions/UnlockFiled.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h3>Unlock Failed</h3>
<h4>You don't have enough tokens to unlock this question.</h4>

<p class="backlink">
    @Html.ActionLink("Back to List", "Index")
</p>